from selenium import webdriver
from selenium.webdriver.common.by import By

import time

driver=webdriver.Chrome()
driver.maximize_window()
driver.get("https://automationbysqatools.blogspot.com/2021/05/dummy-website.html")
driver.implicitly_wait(10)
driver.find_element(By.XPATH,"//input[@value='radio_558']").click()
time.sleep(2)
driver.find_element(By.XPATH,"//input[@name='firstname'][1]").send_keys("Nikhila")
time.sleep(3)
driver.find_element(By.XPATH,"//input[@name='firstname'][2]").send_keys("Joy")
time.sleep(3)
driver.find_element(By.XPATH,"//input[@id='birthday']").send_keys("02-07-1998")
time.sleep(2)
driver.find_element(By.XPATH,"//input[@id='female']").click()
time.sleep(2)
driver.find_element(By.XPATH,"//input[@id='roundtrip']").click()
time.sleep(2)
driver.find_element(By.XPATH,"//input[@id='fromcity']").send_keys("Banglore")
time.sleep(2)
driver.find_element(By.XPATH,"//input[@id='destcity']").send_keys("Bali")
time.sleep(2)
driver.find_element(By.XPATH,"//input[@id='departdate']").send_keys("10-10-2024")
time.sleep(2)
driver.find_element(By.XPATH,"//input[@id='returndate']").send_keys("16-10-2024")
time.sleep(2)
driver.find_element(By.XPATH,"//input[@id='visadate']").send_keys("20-08-2024")
time.sleep(2)
driver.find_element(By.XPATH,"//input[@id='eamil']").click()
time.sleep(2)
driver.find_element(By.XPATH,"//input[@id='billing_name']").send_keys("Nikhila Joy")
time.sleep(2)
driver.find_element(By.XPATH,"//input[@id='billing_phone']").send_keys("8547742482")
time.sleep(2)
driver.find_element(By.XPATH,"//input[@id='billing_email']").send_keys("nikhilajoy11@gmail.com")
time.sleep(2)
driver.find_element(By.XPATH,"//input[@id='billing_address']").send_keys("aghtnf")
time.sleep(2)
driver.find_element(By.XPATH,"//input[@id='postcode']").send_keys("686654")
time.sleep(2)
driver.find_element(By.XPATH,"//input[@id='street_address1']").send_keys("hgfhqgfdhgfdg")
time.sleep(2)
driver.find_element(By.XPATH,"//input[@id='street_address2']").send_keys("sadsdwerfaswdq")
time.sleep(2)
driver.find_element(By.XPATH,"(//input[@value='checkbox'])[5]").click()
time.sleep(4)