import time

from selenium import webdriver
from selenium.webdriver.common.by import By

driver = webdriver.Chrome()
driver.maximize_window()
driver.implicitly_wait(10)
driver.get("https://automationbysqatools.blogspot.com/2021/05/dummy-website.html")
header_element = driver.find_element(By.TAG_NAME, "h1")
time.sleep(5)
driver.find_element(By.XPATH,"(//input[@type='radio'])[2]").click()
driver.find_element(By.ID,"firstname").send_keys("Sangeetha")
time.sleep(5)
driver.find_element(By.XPATH,"(//input[@name='firstname'])[2]").send_keys("kokkonda")
driver.find_element(By.ID,"female").click()
time.sleep(5)
driver.find_element(By.ID,"roundtrip").click()
time.sleep(5)
driver.find_element(By.ID, "fromcity").send_keys("kakinada")
time.sleep(5)
driver.find_element(By.ID, "destcity").send_keys("chennai")
time.sleep(5)
driver.find_element(By.ID,"eamil").click()
time.sleep(5)
driver.find_element(By.ID,"billing_name").send_keys("sangeetha")
driver.find_element(By.ID,"billing_phone").send_keys("9059993936")
driver.find_element(By.ID,"billing_email").send_keys("sangeetha123@gmail.com")
driver.find_element(By.ID,"billing_address").send_keys("No119,f4,sai homes,chennai")
time.sleep(5)
driver.find_element(By.ID,"billing_country").send_keys("India")
time.sleep(5)
driver.find_element(By.ID,"postcode").send_keys("600053")
time.sleep(5)
driver.find_element(By.ID,"street_address1").send_keys("Ambattur,chennai")
time.sleep(5)
driver.find_element(By.XPATH,"(//input[@type='checkbox'])[3]").click()
time.sleep(5)

