name: 2 minutes schedule
'on':
  schedule:
    - cron: 1 * * * *
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      '-name': Linux-command
      run: |
        python --version
        uname -a
